site_name: pymportx
site_author: Víctor Sánchez-Arévalo
site_description: This is the pymportx Python package documentation site. 
nav:
  - Home: index.md
  - pymportx: index copia.md
theme: readthedocs
repo_url: https://github.com/victorsanchezarevalo/pymportx
site_url: https://github.com/victorsanchezarevalo/pymportx
